package forj

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/alecthomas/kong"
	"github.com/goforj/console"
	"gopkg.in/yaml.v3"
)

// writeModuleRenameFixture builds source-only fixtures without running a renderer in the repository.
func writeModuleRenameFixture(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for name, data := range files {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(data), 0o640); err != nil {
			t.Fatal(err)
		}
	}
}

// moduleRenameFixture keeps the original module consistent across the configuration and manifest.
func moduleRenameFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	writeModuleRenameFixture(t, root, map[string]string{
		".goforj.yml": "# Keep this comment\nproject_name: Orders\nmodule_name: 'example.com/old' # module comment\ncustom: {enabled: true}\nrender:\n  module_replaces:\n    example.com/dependency: ../dependency\n",
		"go.mod":      "module example.com/old\n\ngo 1.25.0\n\nrequire example.com/old-extra v1.2.3\nreplace example.com/dependency => ../dependency\n",
		"main.go":     "package main\n\nimport alias \"example.com/old/internal/service\"\n\nfunc main() { alias.Run() }\n",
	})
	return root
}

// TestProjectModuleRenameUpdatesOwnedReferences verifies semantic boundaries, generated files, modes, and repeatability.
func TestProjectModuleRenameUpdatesOwnedReferences(t *testing.T) {
	t.Parallel()
	root := moduleRenameFixture(t)
	unchanged := map[string]string{
		"README.md":                     "example.com/old\n",
		".env":                          "TOKEN=example.com/old\n",
		".git/fixture.go":               "not valid Go: example.com/old",
		"vendor/dependency.go":          "not valid Go: example.com/old",
		"frontend/node_modules/file.go": "not valid Go: example.com/old",
		"integration/go.mod":            "module example.com/old/integration\n\ngo 1.25.0\n",
		"integration/main.go":           "package integration\nimport _ \"example.com/old/internal/service\"\n",
		"bin/app":                       "\x00example.com/old",
	}
	writeModuleRenameFixture(t, root, unchanged)
	writeModuleRenameFixture(t, root, map[string]string{
		"app/admin/wire/wire_gen.go": "// Code generated by Wire. DO NOT EDIT.\npackage wire\nimport . \"example.com/old/internal/service\"\n",
		"internal/info/info.go": "package info\n" +
			"const Module = `example.com/old`\nconst Path = \"example.com/old/internal/service\"\n" +
			"const Other = \"example.com/old-extra/service\"\nconst Text = \"visit example.com/old\"\n" +
			"const Nested = \"example.com/old/integration/service\"\n// example.com/old is historical context.\n",
		"internal/views/page.templ": "package views\n\nimport \"example.com/old/internal/service\"\n\ntempl Page() {\n<p>{ service.Name }</p>\n}\n",
	})
	plan, err := planProjectModuleRename(root, "example.org/new/v2")
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(plan.nested, []string{"integration"}) {
		t.Fatalf("nested modules = %v", plan.nested)
	}
	before := readMakeAppTestFile(t, filepath.Join(root, "main.go"))
	if !strings.Contains(before, "example.com/old/internal/service") {
		t.Fatal("planning changed the source")
	}
	if err := plan.apply(os.Rename); err != nil {
		t.Fatal(err)
	}
	for _, file := range plan.files {
		got, err := os.ReadFile(filepath.Join(root, file.path))
		if err != nil || !bytes.Equal(got, file.after) {
			t.Fatalf("%s not updated: %v", file.path, err)
		}
		info, err := os.Stat(filepath.Join(root, file.path))
		if err != nil || info.Mode().Perm() != file.mode {
			t.Fatalf("%s mode not preserved: %v", file.path, err)
		}
	}
	for path, want := range unchanged {
		if got := readMakeAppTestFile(t, filepath.Join(root, path)); got != want {
			t.Fatalf("changed excluded file %s: %q", path, got)
		}
	}
	info := readMakeAppTestFile(t, filepath.Join(root, "internal/info/info.go"))
	for _, want := range []string{"`example.org/new/v2`", `"example.org/new/v2/internal/service"`, `"example.com/old-extra/service"`, `"visit example.com/old"`, `"example.com/old/integration/service"`, "// example.com/old is historical context."} {
		if !strings.Contains(info, want) {
			t.Fatalf("missing %q in rewritten source: %s", want, info)
		}
	}
	config := readMakeAppTestFile(t, filepath.Join(root, ".goforj.yml"))
	for _, want := range []string{"# Keep this comment", "# module comment", "example.org/new/v2", "../dependency"} {
		if !strings.Contains(config, want) {
			t.Fatalf("missing config content %q: %s", want, config)
		}
	}
	var values map[string]any
	if err := yaml.Unmarshal([]byte(config), &values); err != nil || values["project_name"] != "Orders" || values["custom"] == nil {
		t.Fatalf("unrelated config changed: %v %v", values, err)
	}
	manifest := readMakeAppTestFile(t, filepath.Join(root, "go.mod"))
	for _, want := range []string{"module example.org/new/v2", "go 1.25.0", "require example.com/old-extra v1.2.3", "replace example.com/dependency => ../dependency"} {
		if !strings.Contains(manifest, want) {
			t.Fatalf("missing manifest content %q: %s", want, manifest)
		}
	}
	again, err := planProjectModuleRename(root, "example.org/new/v2")
	if err != nil || len(again.files) != 0 {
		t.Fatalf("repeat rename = %#v, %v", again, err)
	}
}

// TestProjectModuleRenameValidationLeavesFilesUntouched covers every input shape rejected before writing.
func TestProjectModuleRenameValidationLeavesFilesUntouched(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		name, module string
		files        map[string]string
		want         string
	}{
		{name: "empty", want: "required"},
		{name: "whitespace", module: " example.org/new", want: "whitespace"},
		{name: "URL", module: "https://example.org/new", want: "without a URL scheme"},
		{name: "major", module: "example.org/new/v1", want: "major-version suffix"},
		{name: "reserved", module: "toolchain", want: "reserved"},
		{name: "invalid", module: "example.org/new space", want: "invalid"},
		{name: "config syntax", module: "example.org/new", files: map[string]string{".goforj.yml": "["}, want: "parse .goforj.yml"},
		{name: "config duplicate", module: "example.org/new", files: map[string]string{".goforj.yml": "module_name: example.com/old\nmodule_name: example.com/old\n"}, want: "parse .goforj.yml"},
		{name: "config multiple documents", module: "example.org/new", files: map[string]string{".goforj.yml": "module_name: example.com/old\n---\ncustom: value\n"}, want: "single YAML document"},
		{name: "target dependency", module: "example.com/old-extra", want: "already belongs"},
		{name: "target nested", module: "example.org/nested", files: map[string]string{"nested/go.mod": "module example.org/nested\n"}, want: "already belongs"},
		{name: "config missing", module: "example.org/new", files: map[string]string{".goforj.yml": "project_name: Orders\n"}, want: "explicit"},
		{name: "config empty", module: "example.org/new", files: map[string]string{".goforj.yml": ""}, want: "explicit"},
		{name: "config alias", module: "example.org/new", files: map[string]string{".goforj.yml": "name: &module example.com/old\nmodule_name: *module\n"}, want: "explicit"},
		{name: "config anchor", module: "example.org/new", files: map[string]string{".goforj.yml": "module_name: &module example.com/old\n"}, want: "explicit"},
		{name: "manifest syntax", module: "example.org/new", files: map[string]string{"go.mod": "???"}, want: "parse go.mod"},
		{name: "manifest missing module", module: "example.org/new", files: map[string]string{"go.mod": "go 1.25.0\n"}, want: "same module"},
		{name: "mismatch", module: "example.org/new", files: map[string]string{"go.mod": "module example.com/other\n"}, want: "same module"},
		{name: "source syntax", module: "example.org/new", files: map[string]string{"late.go": "package ???"}, want: "parse late.go"},
		{name: "nested syntax", module: "example.org/new", files: map[string]string{"nested/go.mod": "???"}, want: "scan project"},
		{name: "nested missing module", module: "example.org/new", files: map[string]string{"nested/go.mod": "go 1.25.0\n"}, want: "no module directive"},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := moduleRenameFixture(t)
			writeModuleRenameFixture(t, root, test.files)
			before := moduleRenameSnapshot(t, root)
			_, err := planProjectModuleRename(root, test.module)
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("error = %v, want %q", err, test.want)
			}
			if !reflect.DeepEqual(before, moduleRenameSnapshot(t, root)) {
				t.Fatal("failed planning changed files")
			}
		})
	}
}

// TestProjectModuleRenameRejectsMissingAndSpecialFiles prevents partial rewrites and writes through links.
func TestProjectModuleRenameRejectsMissingAndSpecialFiles(t *testing.T) {
	t.Parallel()
	for _, name := range []string{".goforj.yml", "go.mod", "main.go", "nested/go.mod"} {
		t.Run(name, func(t *testing.T) {
			root := moduleRenameFixture(t)
			outside := filepath.Join(t.TempDir(), "outside")
			if err := os.WriteFile(outside, []byte("outside unchanged"), 0o600); err != nil {
				t.Fatal(err)
			}
			path := filepath.Join(root, name)
			_ = os.Remove(path)
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink(outside, path); err != nil {
				t.Skipf("symlinks unavailable: %v", err)
			}
			_, err := planProjectModuleRename(root, "example.org/new")
			if err == nil || !strings.Contains(err.Error(), "regular file") {
				t.Fatalf("error = %v", err)
			}
			if got := readMakeAppTestFile(t, outside); got != "outside unchanged" {
				t.Fatal("symlink target changed")
			}
		})
	}
	for _, name := range []string{".goforj.yml", "go.mod"} {
		root := moduleRenameFixture(t)
		if err := os.Remove(filepath.Join(root, name)); err != nil {
			t.Fatal(err)
		}
		if _, err := planProjectModuleRename(root, "example.org/new"); !errors.Is(err, fs.ErrNotExist) {
			t.Fatalf("missing %s: %v", name, err)
		}
	}
}

// TestProjectModuleRenameWriteFailuresRestoreOriginals injects a failure after both metadata files have changed.
func TestProjectModuleRenameWriteFailuresRestoreOriginals(t *testing.T) {
	t.Parallel()
	root := moduleRenameFixture(t)
	before := moduleRenameSnapshot(t, root)
	plan, err := planProjectModuleRename(root, "example.org/new")
	if err != nil {
		t.Fatal(err)
	}
	calls := 0
	err = plan.apply(func(from, to string) error {
		calls++
		if calls == 3 {
			return fs.ErrPermission
		}
		return os.Rename(from, to)
	})
	if !errors.Is(err, fs.ErrPermission) || calls != 3 {
		t.Fatalf("apply error = %v, calls = %d", err, calls)
	}
	if !reflect.DeepEqual(before, moduleRenameSnapshot(t, root)) {
		t.Fatal("failed rename did not restore original files or leaked temporary files")
	}
}

// TestProjectModuleRenamePreflightWriteFailures prevents predictable failures from leaving mixed module identities.
func TestProjectModuleRenamePreflightWriteFailures(t *testing.T) {
	t.Parallel()
	for _, test := range []string{"changed", "mode changed", "read-only", "deleted", "stage failure"} {
		t.Run(test, func(t *testing.T) {
			root := moduleRenameFixture(t)
			if test == "read-only" {
				if err := os.Chmod(filepath.Join(root, "main.go"), 0o444); err != nil {
					t.Fatal(err)
				}
			}
			plan, err := planProjectModuleRename(root, "example.org/new")
			if err != nil {
				t.Fatal(err)
			}
			switch test {
			case "changed":
				writeModuleRenameFixture(t, root, map[string]string{"main.go": "package changed\n"})
			case "mode changed":
				if err := os.Chmod(filepath.Join(root, "main.go"), 0o444); err != nil {
					t.Fatal(err)
				}
			case "deleted":
				if err := os.Remove(filepath.Join(root, "main.go")); err != nil {
					t.Fatal(err)
				}
			case "stage failure":
				plan.files = append(plan.files, moduleRenameFile{path: "missing/file.go"})
			}
			before := moduleRenameSnapshot(t, root)
			if err := plan.apply(os.Rename); err == nil {
				t.Fatal("apply unexpectedly succeeded")
			}
			if !reflect.DeepEqual(before, moduleRenameSnapshot(t, root)) {
				t.Fatal("preflight failure changed files")
			}
		})
	}
}

// TestProjectRenameModuleCommandWiring exercises no-argument parsing and an explicitly confirmed rename.
func TestProjectRenameModuleCommandWiring(t *testing.T) {
	t.Parallel()
	root := moduleRenameFixture(t)
	writeModuleRenameFixture(t, root, map[string]string{"nested/go.mod": "module example.org/nested\n"})
	var output bytes.Buffer
	command := RootCmd{ProjectRenameModuleCmd: ProjectRenameModuleCmd{root: root, ui: moduleRenameTestConsole("example.org/new\nyes\n", &output)}}
	cli, err := kong.New(&command)
	if err != nil {
		t.Fatal(err)
	}
	context, err := cli.Parse([]string{"project:rename-module"})
	if err != nil {
		t.Fatal(err)
	}
	if err := context.Run(); err != nil {
		t.Fatal(err)
	}
	if got := readMakeAppTestFile(t, filepath.Join(root, "go.mod")); !strings.HasPrefix(got, "module example.org/new\n") {
		t.Fatalf("command did not rename module: %s", got)
	}
	for _, want := range []string{"Current module: example.com/old", "New module name", "New module: example.org/new", "Rename the entire project module and all of its imports? [y/N]", "Renamed Go module", "Leaving nested module unchanged: nested"} {
		if !strings.Contains(output.String(), want) {
			t.Fatalf("missing %q in interactive flow: %s", want, output.String())
		}
	}
}

// TestProjectRenameModulePromptsNeverWriteWithoutConsent covers cancellation, invalid input, preview, EOF, and unchanged names.
func TestProjectRenameModulePromptsNeverWriteWithoutConsent(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		name, input, want string
		dryRun, wantError bool
	}{
		{name: "empty name", input: "\n", want: "canceled"},
		{name: "no", input: "example.org/new\nno\n", want: "canceled"},
		{name: "default no", input: "example.org/new\n\n", want: "canceled"},
		{name: "name EOF", want: "New module name", wantError: true},
		{name: "confirmation EOF", input: "example.org/new\n", want: "[y/N]", wantError: true},
		{name: "invalid then cancel", input: "https://example.org/new\n\n", want: "without a URL scheme"},
		{name: "unchanged", input: "example.com/old\n", want: "already example.com/old"},
		{name: "preview", input: "example.org/new\n", dryRun: true, want: "Dry run complete"},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := moduleRenameFixture(t)
			before := moduleRenameSnapshot(t, root)
			var output bytes.Buffer
			command := ProjectRenameModuleCmd{root: root, DryRun: test.dryRun, ui: moduleRenameTestConsole(test.input, &output)}
			err := command.Run()
			if (err != nil) != test.wantError {
				t.Fatalf("Run() = %v, wantError = %v", err, test.wantError)
			}
			if !reflect.DeepEqual(before, moduleRenameSnapshot(t, root)) {
				t.Fatal("interactive command changed files without confirmation")
			}
			if !strings.Contains(output.String(), test.want) {
				t.Fatalf("missing %q in output: %s", test.want, output.String())
			}
		})
	}
}

// TestProjectRenameModulePromptRetriesInvalidNames keeps a mistyped path inside the interactive flow.
func TestProjectRenameModulePromptRetriesInvalidNames(t *testing.T) {
	t.Parallel()
	root := moduleRenameFixture(t)
	var output bytes.Buffer
	command := ProjectRenameModuleCmd{root: root, ui: moduleRenameTestConsole("bad module\nexample.org/new\ny\n", &output)}
	if err := command.Run(); err != nil {
		t.Fatal(err)
	}
	if strings.Count(output.String(), "New module name") != 2 {
		t.Fatalf("expected retry after invalid input: %s", output.String())
	}
}

// TestProjectRenameModuleRejectsNonInteractiveInput prevents piped or missing input from supplying implicit approval.
func TestProjectRenameModuleRejectsNonInteractiveInput(t *testing.T) {
	t.Parallel()
	root := moduleRenameFixture(t)
	before := moduleRenameSnapshot(t, root)
	var output bytes.Buffer
	enabled := false
	command := ProjectRenameModuleCmd{root: root, ui: console.New(console.Config{
		Stdin: strings.NewReader("example.org/new\nyes\n"), Stdout: &output, Stderr: &output, InteractiveEnabled: &enabled,
	})}
	if err := command.Run(); !errors.Is(err, console.ErrNonInteractive) {
		t.Fatalf("Run() = %v", err)
	}
	if !reflect.DeepEqual(before, moduleRenameSnapshot(t, root)) {
		t.Fatal("non-interactive input changed files")
	}
}

// moduleRenameTestConsole drives the real prompt parser without sharing global console state between tests.
func moduleRenameTestConsole(input string, output *bytes.Buffer) *console.Console {
	interactive, styling := true, false
	return console.New(console.Config{
		Stdin: strings.NewReader(input), Stdout: output, Stderr: output,
		InteractiveEnabled: &interactive, ColorEnabled: &styling, UnicodeEnabled: &styling, Width: 140,
	})
}

// moduleRenameSnapshot records fixture bytes, including any leaked staging files.
func moduleRenameSnapshot(t *testing.T, root string) map[string]string {
	t.Helper()
	files := make(map[string]string)
	if err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		files[path] = string(data)
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	return files
}

// TestProjectRenameModuleReportsFailuresWithoutWriting covers command-level metadata, planning, and write-preflight failures.
func TestProjectRenameModuleReportsFailuresWithoutWriting(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		name, input, want string
	}{
		{name: "metadata", want: "same module"},
		{name: "planning", input: "example.org/new\n", want: "parse main.go"},
		{name: "read-only", input: "example.org/new\nyes\n", want: "read-only"},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := moduleRenameFixture(t)
			switch test.name {
			case "metadata":
				writeModuleRenameFixture(t, root, map[string]string{"go.mod": "module example.org/mismatch\n"})
			case "planning":
				writeModuleRenameFixture(t, root, map[string]string{"main.go": "invalid Go"})
			case "read-only":
				if err := os.Chmod(filepath.Join(root, "main.go"), 0o444); err != nil {
					t.Fatal(err)
				}
			}
			before := moduleRenameSnapshot(t, root)
			var output bytes.Buffer
			command := ProjectRenameModuleCmd{root: root, ui: moduleRenameTestConsole(test.input, &output)}
			if err := command.Run(); err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("Run() = %v, want %q", err, test.want)
			}
			if !reflect.DeepEqual(before, moduleRenameSnapshot(t, root)) {
				t.Fatal("failed command changed files")
			}
		})
	}
}

// TestProjectRenameModuleUsesWorkingDirectory verifies the public command needs no path argument.
func TestProjectRenameModuleUsesWorkingDirectory(t *testing.T) {
	root := moduleRenameFixture(t)
	t.Chdir(root)
	var output bytes.Buffer
	command := ProjectRenameModuleCmd{ui: moduleRenameTestConsole("example.org/new\nyes\n", &output)}
	if err := command.Run(); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(readMakeAppTestFile(t, "go.mod"), "module example.org/new") {
		t.Fatal("command did not use current directory")
	}
}

// TestProjectModuleRenameStagingFailure returns filesystem failures before publishing a temporary file.
func TestProjectModuleRenameStagingFailure(t *testing.T) {
	t.Parallel()
	if path, err := stageModuleRenameFile(t.TempDir(), moduleRenameFile{path: "missing/source.go", mode: 0o644}, []byte("package source\n")); err == nil || path != "" {
		t.Fatalf("stage = %q, %v", path, err)
	}
}

// TestProjectModuleRenamePreservesDependencyNamespaces prevents sibling modules from becoming packages of the new root.
func TestProjectModuleRenamePreservesDependencyNamespaces(t *testing.T) {
	t.Parallel()
	root := moduleRenameFixture(t)
	writeModuleRenameFixture(t, root, map[string]string{
		"go.mod":  "module example.com/old\n\ngo 1.25.0\nrequire example.com/old/lib v1.0.0\nreplace example.com/old/driver => ../driver\n",
		"main.go": "package main\nimport (\n_ \"example.com/old/internal/own\"\n_ \"example.com/old/lib/api\"\n_ \"example.com/old/driver/api\"\n)\n",
	})
	plan, err := planProjectModuleRename(root, "example.org/new")
	if err != nil {
		t.Fatal(err)
	}
	if err := plan.apply(os.Rename); err != nil {
		t.Fatal(err)
	}
	data := readMakeAppTestFile(t, filepath.Join(root, "main.go"))
	for _, want := range []string{"example.org/new/internal/own", "example.com/old/lib/api", "example.com/old/driver/api"} {
		if !strings.Contains(data, want) {
			t.Fatalf("missing %s: %s", want, data)
		}
	}
}

// moduleRenameReadFunc lets a test model an editor changing the project while a prompt waits for input.
type moduleRenameReadFunc func([]byte) (int, error)

// Read invokes the test's input callback using the ordinary console reader contract.
func (f moduleRenameReadFunc) Read(data []byte) (int, error) { return f(data) }

// TestProjectRenameModuleDetectsIdentityChangesWhilePrompting refuses approval for an identity the user was not shown.
func TestProjectRenameModuleDetectsIdentityChangesWhilePrompting(t *testing.T) {
	t.Parallel()
	root := moduleRenameFixture(t)
	var output bytes.Buffer
	var changed map[string]string
	reader := strings.NewReader("example.org/new\nyes\n")
	interactive, styling := true, false
	ui := console.New(console.Config{
		Stdin: moduleRenameReadFunc(func(data []byte) (int, error) {
			if changed == nil {
				writeModuleRenameFixture(t, root, map[string]string{
					".goforj.yml": "module_name: example.org/concurrent\n",
					"go.mod":      "module example.org/concurrent\n",
				})
				changed = moduleRenameSnapshot(t, root)
			}
			return reader.Read(data)
		}),
		Stdout: &output, Stderr: &output, InteractiveEnabled: &interactive, ColorEnabled: &styling,
	})
	if err := (&ProjectRenameModuleCmd{root: root, ui: ui}).Run(); err == nil || !strings.Contains(err.Error(), "changed while prompting") {
		t.Fatalf("Run() = %v", err)
	}
	if !reflect.DeepEqual(changed, moduleRenameSnapshot(t, root)) {
		t.Fatal("command overwrote concurrent changes")
	}
}

// TestProjectModuleRenameReportsRestorationFailures keeps a failed rollback visible and restores unaffected files.
func TestProjectModuleRenameReportsRestorationFailures(t *testing.T) {
	t.Parallel()
	root := moduleRenameFixture(t)
	manifest := readMakeAppTestFile(t, filepath.Join(root, "go.mod"))
	plan, err := planProjectModuleRename(root, "example.org/new")
	if err != nil {
		t.Fatal(err)
	}
	calls := 0
	err = plan.apply(func(from, to string) error {
		calls++
		if calls == 3 {
			path := filepath.Join(root, ".goforj.yml")
			if err := os.Remove(path); err != nil {
				t.Fatal(err)
			}
			if err := os.Mkdir(path, 0o755); err != nil {
				t.Fatal(err)
			}
			return fs.ErrPermission
		}
		return os.Rename(from, to)
	})
	if !errors.Is(err, fs.ErrPermission) || !strings.Contains(err.Error(), "restore .goforj.yml") {
		t.Fatalf("apply = %v", err)
	}
	if got := readMakeAppTestFile(t, filepath.Join(root, "go.mod")); got != manifest {
		t.Fatal("rollback failed to restore an unaffected file")
	}
	if paths, err := filepath.Glob(filepath.Join(root, ".forj-module-*")); err != nil || len(paths) != 0 {
		t.Fatalf("leaked staging files: %v, %v", paths, err)
	}
}
